version: '2.4'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    image: pm2_server
    container_name: pm2_server
    restart: always
    ports:
      - "80:8000"
    cpus: '5'
